### ISSUE TITLE
Error importing libxml2raw.js when type is set to module in package.json

### ISSUE THREAD

**Issue by abeq** [jameslan/libxml2-wasm#38]
There is way to use it on Browser?

```
import {XmlDocument} from './node_modules/libxml2-wasm/lib/index.mjs';
```
But error has occurred as followings:
```
Uncaught SyntaxError: The requested module './libxml2raw.js' does not provide an export named 'default' (at libxml2.mjs:1:8)
```

Please advise.

**Comment by jameslan** [comment]
Do you use any bundler?

Libxml2-wasm's package has multiple files, it's better to bundle it together so that it is much easier to be transferred over the network. 

Is your project ESM or CommonJS module? Libxml2-wasm is ESM, so it will be a little bit different between being called by ESM or CommonJS. 

Please refer to the example in README or in the documentation.

**Comment by jameslan** [comment]
Is
```
"type": "module"
```
In your `package.json`?

**Comment by jameslan** [comment]
Reproduced with `type` set to `module` in package.json.

When it is set, `*.js` is treated as ESM. However, emscripten generated file, libxml2raw.js, is CommonJS.

It is using 
```js
 module.exports = Module;
```
to export. 

This doesn't work in ESM mode.
In another words, the module with export nothing in ESM.

That's why we got error message
```
The requested module './libxml2raw.js' does not provide an export named 'default'
```
